name: daynis_h264_media_stream
description: "A Flutter package for streaming raw H264 video data on the web."
version: 0.0.1
homepage: https://github.com/daynis-olman/daynis_h264_media_stream

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DaynisH264MediaStreamPlugin
        fileName: daynis_h264_media_stream_web.dart

  assets:
    - assets/jmuxer.js