name: daynis_h264_media_stream
description: "A Flutter package for streaming raw H264 video data on the web."
version: 0.0.1
homepage: https://github.com/daynis-olman/daynis_h264_media_stream

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DaynisH264MediaStreamPlugin

  # Reference local assets
  assets:
    - assets/jmuxer.js